import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "./Header";
import Banner from "./Banner";
import SmallCard from "./SmallCard";
import { Ubuntu } from "next/font/google";

const abc = Ubuntu({
  subsets: ["latin"],
  weight: "300",
});

const inter = Inter({ subsets: ["latin"] });

export default function Home({ exploreData, cardsData }) {
  return (
    <>
      <Head>
        <title>Krilya</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/../public/favicon.ico" />
      </Head>
      <Header />
      <Banner className={`relative ${abc.className}`} />
      <main className={`max-w-7xl mx-auto px-8 sm:px16 ${abc.className}`}>
        <section className="pt-6">
          <h2 className="text-3xl font-extrabold pb-5 drop-shadow-md">
            Explore Nearby
          </h2>
          {/* Data endpoint fetching */}

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map(({ img, name, model }) => (
              <SmallCard key={img} img={img} name={name} model={model} />
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-3xl font-bold py-8 font-abc drop-shadow-md">
            Travel
          </h2>
        </section>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch(
    "https://nox281.github.io/Krilya/krilya/public/CarsData.json"
  ).then((res) => res.json());

  const cardsData = await fetch().then((res) => res.json);
  return {
    props: {
      exploreData,
      cardsData,
    },
  };
}
